# Generated by Django 5.0.1 on 2024-01-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
