# Generated by Django 5.0.1 on 2024-01-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=57),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(),
        ),
       
    ]
