# Generated by Django 5.0.1 on 2024-01-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
