# Generated by Django 5.0.1 on 2024-02-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_customuser_is_active_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Document',
        ),
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
