# Generated by Django 5.0.1 on 2024-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_remove_post_document_post_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AddField(
            model_name='post',
            name='Document',
            field=models.FileField(null=True, upload_to='Documents'),
        ),
    ]
