# Generated by Django 5.0.1 on 2024-02-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
