# Generated by Django 5.0.1 on 2024-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_site_qcdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcdocument',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
