# Generated by Django 5.0.1 on 2024-02-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_remove_document_title_document_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('REPORT', 'Report'), ('Invoice', 'invoice'), ('PDQ', 'Pdq'), ('IMAGES', 'Images'), ('OTHERS', 'Others')], default='Report', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
